#!/bin/bash

dependencies=("git" "npm" "psql")
for arg in "${dependencies[@]}" ; do
    if [ -z "$(which $arg)" ] ; then
		cat << EOF
It is necessary to have $arg installed to deploy this project. Please install
it before continuing.
EOF
        exit 1
    fi
done

### CLONE SUBMODULES

cd "$(dirname "$0")"
git submodule update --init --recursive

### STARTING INSTALLATION

project_name="davinci"

cat << EOF
This project was developed and meant to be deployed at the subdirectory \
"$project_name" of a parent project. The project will be available at \
the public URL /$project_name . Please ensure that nginx or whatever proxy \
you might be using is configured properly.
EOF

npm i
cd "client"
npm i
npm audit fix
npm run build

### CONFIGURING POSTGRES

cd "../install"

cat << EOF
Now we will configure PostgreSQL. You might need to type in your password. \
For the database name, anything goes, but it is advised to use the name \
"$project_name" for clarity.
EOF

./install

cd ".."
cat << EOF
Everything should be ready for deployment. Run the server with \
"npm run prod" .
EOF