#!/bin/bash

sed -ri "s/\[yourproject\]/${project_name}/ ; s/\[yourport\]/${port}/" "$new_conf_file"
cp "$path_to_script"/conf/project.conf "/etc/nginx/conf.d/${project_name}.conf"
echo -e "127.0.0.1\t${project_name}.localdev" >> /etc/hosts
systemctl restart nginx