#!/usr/bin/env bash

get_env="./lib/bash_common/get_env $(dirname "$0")/client/.env"

public_url=$($get_env PUBLIC_URL)
host="vulpi-davinci.localdev"
url="$host/$public_url/products"
url="http://${url/\/\//\/}"

path="$(dirname "$0")/img/"

echo "POST request will be sent to $url. Directory with images is $path"

function post_product {
	curl -L -X POST \
		-F "picture=@${path}$1" \
		-F "prodName=$2" \
		-F "prodDescr=$3" \
		-F "prodPrice=$4" \
		-F "prodInStock=$5" \
		"$url"
}

# We have only 12 items but we would like to insert more of them,
# in order to be able to fully grasp the navigation UI.
# So, we will cycle through them.

for i in {1..5} ; do

post_product "compass.png" \
	"Compass" \
	"The wisest men only follow their own directions. Made in China." \
	"1.98" \
	"5"
post_product "feather.png" \
	"Feather" \
	"For practicing your calligraphy and taking notes of the groceries list" \
	"7.98" \
	"2"
post_product "thermometer.jpg" \
	"Thermometer" \
	"An instrument made for measuring temperature. Keep away from children!" \
	"9.99" \
	"10"
post_product "candles.jpg" \
	"Candles" \
	"Sometimes a dedicated artist will need to work into the night... too bad electricity wasn't yet invented! Contains 6 units." \
	"1.49" \
	"87"
post_product "microscope.png" \
	"Microscope" \
	"I guess that wasn't even invented in the Renaissance, but certainly a Renaissance fellow could benefit from it" \
	"3.141596535" \
	"12"
post_product "magnifying-glass.jpg" \
	"Magnifying glass" \
	"See better, see bigger" \
	"3.44" \
	"6.99"
post_product "small-canvas.jpg" \
	"Small canvas" \
	"A canvas with dimensions 20x15cm, ideal for portraits" \
	"9.99" \
	"50"
post_product "medium-canvas.jpg" \
    "Medium canvas" \
    "A canvas with dimensions 40x30cm, ideal for bolder paintings" \
	"29.99" \
    "27"
post_product "giant-canvas.jpg" \
    "Large canvas" \
    "Warming up to paint entire cathedrals? This 100x100cm canvas will get you ready for it!" \
    "129.99" \
    "9"
post_product "basket-of-fruits.jpg" \
    "Basket of fruits" \
    "How do you feel about painting some still nature? This is the perfect motive for you! Not recommended for human consumption." \
    "7.99" \
    "5"
post_product "surgeon-kit.jpeg" \
    "Surgeon Starter Pack" \
    "If you are serious about painting, you have to learn some anatomy. Luckily, we have separated this starter kit just for you!" \
    "99.89" \
    "12"
post_product "brush-collection.jpg" \
    "Brush collection" \
    "Some fine brushes made with sable fur. Just joking, it is all vegan!" \
    "179.89" \
    "3"

done