#!/bin/bash

# Check if directories actually contain anything before trying to move files
dirs=( "/etc/nginx/conf.d" "/etc/nginx/sites-available" "/etc/nginx/sites-enabled")
for arg in "${dirs[@]}" ; do
    if find "$arg" -type f | read ; then
        if [ ! -d "$arg.bkp" ] ; then
            mkdir "$arg.bkp"
        fi
        mv "$arg"/* "$arg.bkp/"
    fi
done

sed -ri "s/\[yourproject\]/${project_name}/ ; s/\[yourport\]/${port}/" "$new_conf_file"
cp "$path_to_script"/conf/project.conf "/etc/nginx/conf.d/${project_name}.conf"
systemctl restart nginx