#!/bin/bash

if [ -z "$(which python3)" ] ; then
	>&2 echo "python must be installed to run this script"
fi

source "$(dirname "$0")/info"

year=$(date +%Y)
os_info_1="$(uname -sr) ($(uname -p))"
os_info_2="$(uname -v)"

short_header=$("$(dirname "$0")/short_header" -n)

long_header=$(cat << EOF
$short_header

$disclaimer

Developed in $os_info_1
$os_info_2
EOF
)

python_script="$(dirname "$0")/square_it.py"
$python_script "$long_header"

echo ""
