#!/bin/bash

sed -ri "s/\[yourproject\]/${project_name}/g ; s/\[yourport\]/${port}/g" "$new_conf_file"
cp "$path_to_script"/conf/project.conf "/etc/nginx/conf.d/${project_name}.conf"

domain="${project_name}.localdev"
if ! grep -q "$domain" /etc/hosts ; then
    echo -e "127.0.0.1\t${project_name}.localdev" >> /etc/hosts
fi
systemctl restart nginx