#!/bin/bash

env_file="../.env"

uname_key="POSTGRES_USER"
passwd_key="POSTGRES_PASSWORD"
host_key="POSTGRES_HOST"
db_key="POSTGRES_DATABASE"
port_key="POSTGRES_PORT"

uname=$(sed -nr "s/^$uname_key=(.+)$/\1/p" $env_file)
passwd=$(sed -nr "s/^$passwd_key=(.+)$/\1/p" $env_file)
host=$(sed -nr "s/^$host_key=(.+)$/\1/p" $env_file)
db=$(sed -nr "s/^$db_key=(.+)$/\1/p" $env_file)
port=$(sed -nr "s/^$port_key=(.+)$/\1/p" $env_file)

echo -e "\n\nWe will now populate the created database $db"

for sql_file in *.sql ; do
    echo "Reading file $sql_file ..."
    PGPASSWORD="$passwd" psql -U "$uname" -h "$host" -d "$db" \
        -p "$port" -f "$sql_file"
done