#!/bin/bash

############################################################
# Messages

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
no_color="\033[0m"

check="${green}CHECK${no_color}"
error="${red}ERROR${no_color}"
success="${green}SUCCESS${no_color}"
done="${green}Done${no_color}"

