#!/bin/bash

# The following line is everything that must be changed when deploying in the future.
database="davinci"

uname="${database}_admin"
passwd="$(pwgen -s 10 1)"
host="127.0.0.1"
port=5432

environment_file="../.env"

text="To run this script, you will need to log in as a super user in PostgreSQL server. \
Usually, this corresponds to Unix ''postgres'' account. \
If you are in the sudoers group, it will suffice to type in your account password below."

echo "$text"

sudo su postgres \
    -c "psql -c \"CREATE USER $uname with encrypted password '$passwd'; \" \
    -c \"CREATE DATABASE $database; \" \
    -c \"GRANT ALL PRIVILEGES ON DATABASE $database TO $uname; \" "

echo -e "\nStarting database...\n"

text="If everything ran successfully, you can now log in to psql with the command:

    psql -h $host -p $port -d $database -U $uname

Then type in the password: ''$passwd''."

echo -e "$text"

text="\
POSTGRES_USER=$uname
POSTGRES_PASSWORD=$passwd
POSTGRES_HOST=$host
POSTGRES_DATABASE=$database
POSTGRES_PORT=$port"

echo "$text" > $environment_file;

echo -e "New credentials were saved to file ''$environment_file'', " \
    "the file on project root holding environment variables"
