#!/bin/bash

source "$(dirname "$0")/messages"

print_header="$(dirname "$0")/header_creator/short_header"
>&2 $print_header

# The following line is everything that must be changed when deploying in the future.

database="davinci"
uname="${database}_admin"

environment_file="../.env"
if [ ! -s "$environment_file" ] ; then
	>&2 echo -e "${error} There is no environment file. Have you installed properly?"
	exit 1
fi

>&2 cat << EOF
To uninstall, you will need to log in to Postgres as a super-user. Please type in your password in order to have sudo access.
EOF

sudo -i -u postgres bash << EOF || exit 1
psql -c "DROP DATABASE $database; " \
-c "DROP USER $uname; " >&2
EOF

rm "$environment_file"
echo -e "${done}"
