#!/usr/bin/env bash

ok=0
err_bad_usage=1
err_non_existent=2
err_not_an_img=3

if [ $# -ne 1 ] ; then
    >&2 echo "Bad usage. Please supply file name as only parameter"
    exit $err_bad_usage
fi

if [ ! -f "$1" ] ; then
    >&2 echo "File $1 does not exist"
    exit $err_non_existent
fi

if ! file "$1" | grep -q "image" ; then
    >&2 echo "Could not process file. It does not seem to be an image"
    exit $err_not_an_img
fi

# Strip all metadata from file
exiftool -overwrite_original -all= "$1" &> /dev/null

# A series of hacks around here. Later we need to refactor this

# Reduce resolution if too large
"$(dirname "$0")"/pic_resize "$1"

# Print md5sum from processed file
(md5sum "$1.jpeg" 2> /dev/null | \
	cut -d" " -f1 2> /dev/null | \
	tr -d "\n") || exit 1

